"""Public C049 k=12 proof-input freeze; evaluator remains unexecuted."""
from __future__ import annotations
import hashlib,json
BASE='research/real_math/millennium/p_vs_np';C='C049-K12-FIRST-ADMISSIBLE-OVERLAP-SEPARATION-v1';F='2026-08-12T04:38:00Z';E=f'{BASE}/05_falsification/c049_k12_overlap_evaluator.py';ER='18d40ecbc9c3233cb7c60ae6043d782e9eabcbe1d3c4ce0b9416d4e63b3d0176';CH='sha256:2f8f1f12acb42d177f53d0fb7695d03d1d5a44922bf8411fad3503c2472b649c'
PATHS={'certificate':f'{BASE}/04_candidates/O9d12a2a1b_C049_K12_PROOF_CERTIFICATE_FREEZE_20260812.json','authorization':f'{BASE}/09_trace/O9d12a2a1b_C049_POST_FREEZE_PROOF_CHECK_AUTHORIZATION_20260812.json','chronology':f'{BASE}/09_trace/O9d12a2a1b_C049_PUBLIC_FREEZE_CHRONOLOGY_20260812.json'}
def h(v):return 'sha256:'+hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()).hexdigest()
def seal(v):r=dict(v);r['artifact_hash']='';r['artifact_hash']=h(r);return r
def build_documents():
 rows=[
 {'obligation_id':'MINIMAL_K_JUSTIFICATION','status':'PROVED','evidence_pointer':'certificate#O1','proof':'Any one-clause CNF is satisfiable: choose an assignment satisfying one of its literals. Thus canonical UNSAT requires m>=2. Canonical length is 8+(2 floor(log2 v)+1)+(2 floor(log2 m)+1)+3m(1+bit_length(v)), before optional padding. With v>=1,m>=2 this is at least 8+1+3+12=24, already even. Hence H_k is empty for k<12 and k=12 is first admissible.'},
 {'obligation_id':'K12_CANONICAL_UNSAT_PARAMETER_FORCING','status':'PROVED','evidence_pointer':'certificate#O2','proof':'At total length 24 every lower bound in O1 is equality. Therefore v=1 and m=2. The raw length is 24, so optional padding is absent. MAGIC||gamma(1)||gamma(2)=11100101||1||010 has length 12, placing the equal split exactly before the payload.'},
 {'obligation_id':'K12_SUFFIX_ROW_FIXED_BIT','status':'PROVED','evidence_pointer':'certificate#O3','proof':'For v=1 each of six literals is encoded as sign||1. Thus c is 12 payload bits and h=1||c. Zero-indexed bit 4 of h is the variable-code bit of the second literal and equals 1.'},
 {'obligation_id':'K13_CANONICAL_PREFIX_FIXED_BIT','status':'PROVED','evidence_pointer':'certificate#O4','proof':'Every p in P_13 is the first 13 bits of a canonical length-26 word and therefore begins with MAGIC=11100101. Its zero-indexed bit 4 equals MAGIC[4]=0.'},
 {'obligation_id':'BIT4_SEPARATION','status':'PROVED','evidence_pointer':'certificate#O5','proof':'O3 fixes bit 4 to 1 on every h in H_12, whereas O4 fixes bit 4 to 0 on every p in P_13. Exact equality is impossible, so H_12 intersection P_13 is empty.'},
 {'obligation_id':'SWAPPED_REDUCTION_PRESERVED','status':'PROVED','evidence_pointer':'certificate#O6','proof':'No decoder, split, or coordinate map changes. For x=r||c the transposed query remains (2^12+c,r), exactly the C048 endpoint-swapped reduction.'}]
 cert=seal({'schema_version':'1.0.0','certificate_id':'PNP-C049-K12-PROOF-CERTIFICATE-20260812','candidate_id':C,'candidate_artifact_hash':CH,'frozen_at':F,'obligations':rows,'scoped_conclusion_if_records_validate':'H_12 intersection P_13 is empty; no conclusion for any k>12.','nonvacuity_note':'Canonical UNSAT length-24 syntax is nonvacuous: v=1,m=2 permits (z OR z OR z) AND (NOT z OR NOT z OR NOT z). The separation proof does not depend on choosing or evaluating this instance.','falsifier':'Any canonical UNSAT word below length 24, alternative parameters at length 24, H_12 label with bit 4 zero, P_13 label with bit 4 one, or exact common label refutes a corresponding obligation.','scope':['k=12 only','exact C041 grammar/equal split','C048 swapped reduction retained','no k>12, cover/lower-bound, novelty, or root result'],'authority':{'same_context_hand_proof':True,'formal':False,'independent':False,'root':'OPEN'},'credit':{'mathematical':['minimality','parameter forcing','fixed-bit separation','swapped reduction preservation'],'software_process':0,'ci_schema_hash_runtime':0}})
 auth=seal({'schema_version':'1.0.0','authorization_id':'PNP-C049-K12-POST-FREEZE-PROOF-CHECK-20260812','candidate_id':C,'certificate_artifact_hash':cert['artifact_hash'],'evaluator_path':E,'evaluator_raw_sha256':ER,'proof_check_authorized':True,'authorized_operation':'evaluate_certificate(exact_certificate, exact_authorization)','decoder_access_authorized':False,'k_enumeration_authorized':False,'target_access_authorized':False,'authorization_effect':'record completeness only; no semantic, k>12, theorem, novelty, or root authority'})
 ch=seal({'schema_version':'1.0.0','chronology_id':'PNP-C049-K12-PUBLIC-PROOF-INPUT-FREEZE-20260812','candidate_id':C,'candidate_public_freeze':{'head_commit':'eca574609057e71cabee3e132ddc9bd485a58062','merge_commit':'17208e34bdd55f12c02d9709eab26381f7b479da','pull_request':294},'proof_inputs':[{'path':PATHS['certificate'],'artifact_hash':cert['artifact_hash']},{'path':PATHS['authorization'],'artifact_hash':auth['artifact_hash']}],'status':'TO_BE_PUBLISHED_BEFORE_EVALUATOR_EXECUTION','target_access':{'decoder_executed':False,'evaluator_executed':False,'k_enumerated':False},'scope':'k=12 only','credit':{'mathematical_result':False,'software_assurance':0}})
 return {'certificate':cert,'authorization':auth,'chronology':ch}
if __name__=='__main__':print(json.dumps(build_documents(),indent=2,sort_keys=True))
